(function(){'use strict';var m,aa="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},p="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;function r(){r=function(){};p.Symbol||(p.Symbol=ba)}var ba=function(){var a=0;return function(b){return"jscomp_symbol_"+(b||"")+a++}}();
function t(){r();var a=p.Symbol.iterator;a||(a=p.Symbol.iterator=p.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&aa(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return ca(this)}});t=function(){}}function ca(a){var b=0;return da(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})}function da(a){t();a={next:a};a[p.Symbol.iterator]=function(){return this};return a}function u(a){t();var b=a[Symbol.iterator];return b?b.call(a):ca(a)}
function ea(a){if(!(a instanceof Array)){a=u(a);for(var b,c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a}function v(a,b){if(b){var c=p;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&aa(c,a,{configurable:!0,writable:!0,value:b})}}
v("Array.prototype.find",function(a){return a?a:function(a,c){a:{var b=this;b instanceof String&&(b=String(b));for(var e=b.length,f=0;f<e;f++){var g=b[f];if(a.call(c,g,f,b)){a=g;break a}}a=void 0}return a}});v("Array.from",function(a){return a?a:function(a,c,d){t();c=null!=c?c:function(a){return a};var b=[],f=a[Symbol.iterator];if("function"==typeof f){a=f.call(a);for(var g=0;!(f=a.next()).done;)b.push(c.call(d,f.value,g++))}else for(f=a.length,g=0;g<f;g++)b.push(c.call(d,a[g],g));return b}});
function w(a,b){return Object.prototype.hasOwnProperty.call(a,b)}var fa="function"==typeof Object.assign?Object.assign:function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(d)for(var e in d)w(d,e)&&(a[e]=d[e])}return a};v("Object.assign",function(a){return a||fa});
v("WeakMap",function(a){function b(a){this.a=(f+=Math.random()+1).toString();if(a){r();t();a=u(a);for(var b;!(b=a.next()).done;)b=b.value,this.set(b[0],b[1])}}function c(a){w(a,e)||aa(a,e,{value:{}})}function d(a){var b=Object[a];b&&(Object[a]=function(a){c(a);return b(a)})}if(function(){if(!a||!Object.seal)return!1;try{var b=Object.seal({}),c=Object.seal({}),d=new a([[b,2],[c,3]]);if(2!=d.get(b)||3!=d.get(c))return!1;d.delete(b);d.set(c,4);return!d.has(b)&&4==d.get(c)}catch(k){return!1}}())return a;
var e="$jscomp_hidden_"+Math.random();d("freeze");d("preventExtensions");d("seal");var f=0;b.prototype.set=function(a,b){c(a);if(!w(a,e))throw Error("WeakMap key fail: "+a);a[e][this.a]=b;return this};b.prototype.get=function(a){return w(a,e)?a[e][this.a]:void 0};b.prototype.has=function(a){return w(a,e)&&w(a[e],this.a)};b.prototype.delete=function(a){return w(a,e)&&w(a[e],this.a)?delete a[e][this.a]:!1};return b});
v("Map",function(a){function b(){var a={};return a.l=a.next=a.head=a}function c(a,b){var c=a.a;return da(function(){if(c){for(;c.head!=a.a;)c=c.l;for(;c.next!=c.head;)return c=c.next,{done:!1,value:b(c)};c=null}return{done:!0,value:void 0}})}function d(a,b){var c=b&&typeof b;"object"==c||"function"==c?f.has(b)?c=f.get(b):(c=""+ ++g,f.set(b,c)):c="p_"+b;var d=a.b[c];if(d&&w(a.b,c))for(a=0;a<d.length;a++){var e=d[a];if(b!==b&&e.key!==e.key||b===e.key)return{id:c,list:d,index:a,h:e}}return{id:c,list:d,
index:-1,h:void 0}}function e(a){this.b={};this.a=b();this.size=0;if(a){a=u(a);for(var c;!(c=a.next()).done;)c=c.value,this.set(c[0],c[1])}}if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var b=Object.seal({x:4}),c=new a(u([[b,"s"]]));if("s"!=c.get(b)||1!=c.size||c.get({x:4})||c.set({x:4},"t")!=c||2!=c.size)return!1;var d=c.entries(),e=d.next();if(e.done||e.value[0]!=b||"s"!=e.value[1])return!1;e=d.next();return e.done||4!=e.value[0].x||
"t"!=e.value[1]||!d.next().done?!1:!0}catch(q){return!1}}())return a;r();t();var f=new WeakMap;e.prototype.set=function(a,b){a=0===a?0:a;var c=d(this,a);c.list||(c.list=this.b[c.id]=[]);c.h?c.h.value=b:(c.h={next:this.a,l:this.a.l,head:this.a,key:a,value:b},c.list.push(c.h),this.a.l.next=c.h,this.a.l=c.h,this.size++);return this};e.prototype.delete=function(a){a=d(this,a);return a.h&&a.list?(a.list.splice(a.index,1),a.list.length||delete this.b[a.id],a.h.l.next=a.h.next,a.h.next.l=a.h.l,a.h.head=
null,this.size--,!0):!1};e.prototype.clear=function(){this.b={};this.a=this.a.l=b();this.size=0};e.prototype.has=function(a){return!!d(this,a).h};e.prototype.get=function(a){return(a=d(this,a).h)&&a.value};e.prototype.entries=function(){return c(this,function(a){return[a.key,a.value]})};e.prototype.keys=function(){return c(this,function(a){return a.key})};e.prototype.values=function(){return c(this,function(a){return a.value})};e.prototype.forEach=function(a,b){for(var c=this.entries(),d;!(d=c.next()).done;)d=
d.value,a.call(b,d[1],d[0],this)};e.prototype[Symbol.iterator]=e.prototype.entries;var g=0;return e});
v("Promise",function(a){function b(a){this.b=0;this.c=void 0;this.a=[];var b=this.f();try{a(b.resolve,b.reject)}catch(n){b.reject(n)}}function c(){this.a=null}function d(a){return a instanceof b?a:new b(function(b){b(a)})}if(a)return a;c.prototype.b=function(a){null==this.a&&(this.a=[],this.f());this.a.push(a)};c.prototype.f=function(){var a=this;this.c(function(){a.i()})};var e=p.setTimeout;c.prototype.c=function(a){e(a,0)};c.prototype.i=function(){for(;this.a&&this.a.length;){var a=this.a;this.a=
[];for(var b=0;b<a.length;++b){var c=a[b];a[b]=null;try{c()}catch(k){this.g(k)}}}this.a=null};c.prototype.g=function(a){this.c(function(){throw a;})};b.prototype.f=function(){function a(a){return function(d){c||(c=!0,a.call(b,d))}}var b=this,c=!1;return{resolve:a(this.u),reject:a(this.g)}};b.prototype.u=function(a){if(a===this)this.g(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof b)this.A(a);else{a:switch(typeof a){case "object":var c=null!=a;break a;case "function":c=!0;
break a;default:c=!1}c?this.s(a):this.i(a)}};b.prototype.s=function(a){var b=void 0;try{b=a.then}catch(n){this.g(n);return}"function"==typeof b?this.B(b,a):this.i(a)};b.prototype.g=function(a){this.j(2,a)};b.prototype.i=function(a){this.j(1,a)};b.prototype.j=function(a,b){if(0!=this.b)throw Error("Cannot settle("+a+", "+b+"): Promise already settled in state"+this.b);this.b=a;this.c=b;this.o()};b.prototype.o=function(){if(null!=this.a){for(var a=0;a<this.a.length;++a)f.b(this.a[a]);this.a=null}};
var f=new c;b.prototype.A=function(a){var b=this.f();a.v(b.resolve,b.reject)};b.prototype.B=function(a,b){var c=this.f();try{a.call(b,c.resolve,c.reject)}catch(k){c.reject(k)}};b.prototype.then=function(a,c){function d(a,b){return"function"==typeof a?function(b){try{e(a(b))}catch(I){f(I)}}:b}var e,f,g=new b(function(a,b){e=a;f=b});this.v(d(a,e),d(c,f));return g};b.prototype.catch=function(a){return this.then(void 0,a)};b.prototype.v=function(a,b){function c(){switch(d.b){case 1:a(d.c);break;case 2:b(d.c);
break;default:throw Error("Unexpected state: "+d.b);}}var d=this;null==this.a?f.b(c):this.a.push(c)};b.resolve=d;b.reject=function(a){return new b(function(b,c){c(a)})};b.race=function(a){return new b(function(b,c){for(var e=u(a),f=e.next();!f.done;f=e.next())d(f.value).v(b,c)})};b.all=function(a){var c=u(a),e=c.next();return e.done?d([]):new b(function(a,b){function f(b){return function(c){g[b]=c;h--;0==h&&a(g)}}var g=[],h=0;do g.push(void 0),h++,d(e.value).v(f(g.length-1),b),e=c.next();while(!e.done)})};
return b});var y=this;function z(){}
function ha(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function A(a){return"function"==ha(a)}function ja(a,b,c){return a.call.apply(a.bind,arguments)}function ka(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}
function B(a,b,c){Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?B=ja:B=ka;return B.apply(null,arguments)}function C(a,b){function c(){}c.prototype=b.prototype;a.na=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.ma=function(a,c,f){for(var d=Array(arguments.length-2),e=2;e<arguments.length;e++)d[e-2]=arguments[e];return b.prototype[c].apply(a,d)}};function E(a){if(Error.captureStackTrace)Error.captureStackTrace(this,E);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))}C(E,Error);E.prototype.name="CustomError";var la=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};function ma(a,b){return a<b?-1:a>b?1:0};var F;a:{var na=y.navigator;if(na){var oa=na.userAgent;if(oa){F=oa;break a}}F=""}function G(a){return-1!=F.indexOf(a)};function pa(a){pa[" "](a);return a}pa[" "]=z;function qa(a,b){var c=ra;return Object.prototype.hasOwnProperty.call(c,a)?c[a]:c[a]=b(a)};var sa=G("Opera"),H=G("Trident")||G("MSIE"),ta=G("Edge"),ua=G("Gecko")&&!(-1!=F.toLowerCase().indexOf("webkit")&&!G("Edge"))&&!(G("Trident")||G("MSIE"))&&!G("Edge"),va=-1!=F.toLowerCase().indexOf("webkit")&&!G("Edge"),wa;
a:{var xa="",ya=function(){var a=F;if(ua)return/rv:([^\);]+)(\)|;)/.exec(a);if(ta)return/Edge\/([\d\.]+)/.exec(a);if(H)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(va)return/WebKit\/(\S+)/.exec(a);if(sa)return/(?:Version)[ \/]?(\S+)/.exec(a)}();ya&&(xa=ya?ya[1]:"");if(H){var J,za=y.document;J=za?za.documentMode:void 0;if(null!=J&&J>parseFloat(xa)){wa=String(J);break a}}wa=xa}var Aa=wa,ra={};
function Ba(a){return qa(a,function(){for(var b=0,c=la(String(Aa)).split("."),d=la(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var g=c[f]||"",h=d[f]||"";do{g=/(\d*)(\D*)(.*)/.exec(g)||["","","",""];h=/(\d*)(\D*)(.*)/.exec(h)||["","","",""];if(0==g[0].length&&0==h[0].length)break;b=ma(0==g[1].length?0:parseInt(g[1],10),0==h[1].length?0:parseInt(h[1],10))||ma(0==g[2].length,0==h[2].length)||ma(g[2],h[2]);g=g[3];h=h[3]}while(0==b)}return 0<=b})};function Ca(a,b){this.b=a;this.f=b;this.a={};this.c=!0;if(0<this.b.length){for(a=0;a<this.b.length;a++){b=this.b[a];var c=b[0];this.a[c.toString()]=new Da(c,b[1])}this.c=!0}}Ca.prototype.m=function(){if(this.c){if(this.f){var a=this.a,b;for(b in a)if(Object.prototype.hasOwnProperty.call(a,b)){var c=a[b].a;c&&c.m()}}}else{this.b.length=0;a=K(this);a.sort();for(b=0;b<a.length;b++){var d=this.a[a[b]];(c=d.a)&&c.m();this.b.push([d.key,d.value])}this.c=!0}return this.b};
function L(a){this.a=0;this.b=a}L.prototype.next=function(){return this.a<this.b.length?{done:!1,value:this.b[this.a++]}:{done:!0,value:void 0}};"undefined"!=typeof Symbol&&(L.prototype[Symbol.iterator]=function(){return this});function Ea(a){var b=[],c=K(a);c.sort();for(var d=0;d<c.length;d++){var e=a.a[c[d]];b.push([e.key,e.value])}return b}m=Ca.prototype;m.entries=function(){var a=[],b=K(this);b.sort();for(var c=0;c<b.length;c++){var d=this.a[b[c]];a.push([d.key,Fa(this,d)])}return new L(a)};
m.keys=function(){var a=[],b=K(this);b.sort();for(var c=0;c<b.length;c++)a.push(this.a[b[c]].key);return new L(a)};m.values=function(){var a=[],b=K(this);b.sort();for(var c=0;c<b.length;c++)a.push(Fa(this,this.a[b[c]]));return new L(a)};m.set=function(a,b){var c=new Da(a);this.f?(c.a=b,c.value=b.m()):c.value=b;this.a[a.toString()]=c;this.c=!1;return this};function Fa(a,b){return a.f?(b.a||(b.a=new a.f(b.value)),b.a):b.value}m.get=function(a){if(a=this.a[a.toString()])return Fa(this,a)};
m.has=function(a){return a.toString()in this.a};function K(a){a=a.a;var b=[],c;for(c in a)Object.prototype.hasOwnProperty.call(a,c)&&b.push(c);return b}function Da(a,b){this.key=a;this.value=b;this.a=void 0};function M(){}var Ga="function"==typeof Uint8Array;function N(a,b,c){a.a=null;b||(b=[]);a.j=void 0;a.f=-1;a.b=b;a:{if(b=a.b.length){--b;var d=a.b[b];if(d&&"object"==typeof d&&"array"!=ha(d)&&!(Ga&&d instanceof Uint8Array)){a.g=b-a.f;a.c=d;break a}}a.g=Number.MAX_VALUE}a.i={};if(c)for(b=0;b<c.length;b++)d=c[b],d<a.g?(d+=a.f,a.b[d]=a.b[d]||O):(Ha(a),a.c[d]=a.c[d]||O)}var O=[];function Ha(a){var b=a.g+a.f;a.b[b]||(a.c=a.b[b]={})}
function Ia(a,b){if(b<a.g){b+=a.f;var c=a.b[b];return c===O?a.b[b]=[]:c}if(a.c)return c=a.c[b],c===O?a.c[b]=[]:c}function P(a,b,c){a=Ia(a,b);return null==a?c:a}function Ja(a,b,c){a.a||(a.a={});if(b in a.a)return a.a[b];var d=Ia(a,b);if(!d){var e=d=[];b<a.g?a.b[b+a.f]=e:(Ha(a),a.c[b]=e)}return a.a[b]=new Ca(d,c)}function Ka(a){var b=La;a.a||(a.a={});if(!a.a[9]){var c=Ia(a,9);c&&(a.a[9]=new b(c))}return a.a[9]}
function Q(a,b,c){a.a||(a.a={});if(!a.a[c]){if(c<a.g){var d=c+a.f;var e=a.b[d];d=e===O?a.b[d]=[]:e}else e=a.c[c],d=e===O?a.c[c]=[]:e;e=[];for(var f=0;f<d.length;f++)e[f]=new b(d[f]);a.a[c]=e}b=a.a[c];b==O&&(b=a.a[c]=[]);return b}function Ma(a){if(a.a)for(var b in a.a){var c=a.a[b];if("array"==ha(c))for(var d=0;d<c.length;d++)c[d]&&c[d].m();else c&&c.m()}}M.prototype.m=function(){Ma(this);return this.b};function Na(a,b){return new a(b?JSON.parse(b):null)}M.prototype.toString=function(){Ma(this);return this.b.toString()};function Oa(a){N(this,a,null)}C(Oa,M);function Pa(a){N(this,a,Qa)}C(Pa,M);function Ra(a){N(this,a,Sa)}C(Ra,M);function La(a){N(this,a,null)}C(La,M);var Qa=[1],Sa=[2,7];function Ta(a){N(this,a,Ua)}C(Ta,M);function Va(a){N(this,a,Wa)}C(Va,M);function Xa(a){N(this,a,Ya)}C(Xa,M);var Ua=[1,2],Wa=[3,4,5],Ya=[2];function Za(a){N(this,a,null)}C(Za,M);function $a(a){N(this,a,ab)}C($a,M);var ab=[1];function R(a){var b=void 0===b?document:b;return b.querySelector(a)}function bb(a){var b=void 0===b?document:b;return(a=b.querySelectorAll(a))?Array.from(a):[]}function S(a,b,c){b.addEventListener&&b.addEventListener(a,c)}function cb(a){if(a)for(;a.lastChild;)a.removeChild(a.lastChild)}
var db={value:1,id:"local-client",name:"Client Engine (Local)",tag:"l"},eb={value:2,id:"local-server",name:"Server Engine (Local)",tag:"l"},fb={value:3,id:"local-server-adjuster",name:"Server Engine with Adjuster (Local)",tag:"l"},gb={value:4,id:"prod-client",name:"Client Engine (Prod)",tag:"p"},hb={value:5,id:"prod-server",name:"Server Engine (Prod)",tag:"p"},ib={value:6,id:"prod-server-adjuster",name:"Server Engine with Adjuster (Prod)",tag:"p"},jb={value:7,id:"canary-client",name:"Client Engine (Canary)",
tag:"c"},kb={value:8,id:"canary-server",name:"Server Engine (Canary)",tag:"c"},lb={value:9,id:"canary-server-adjuster",name:"Server Engine with Adjuster (Canary)",tag:"c"};
function mb(a,b,c){b=void 0===b?"":b;c=void 0===c?"":c;switch(a){case db:return"generated/engine_bin.js";case eb:case fb:return"generated/debug_server_engine_bin.js";case gb:return"http://pagead2.googlesyndication.com/pagead/gadgets/mysidia/"+("versioned_data/"+b+"/engine/")+"client_engine.js";case hb:case ib:return"http://pagead2.googlesyndication.com/pagead/gadgets/mysidia/"+("versioned_data/"+b+"/engine/")+"debug_engine.js";case jb:return"http://pagead2.googlesyndication.com/pagead/gadgets/mysidia/"+
("versioned_data/"+c+"/engine/")+"client_engine.js";case kb:case lb:return"http://pagead2.googlesyndication.com/pagead/gadgets/mysidia/"+("versioned_data/"+c+"/engine/")+"debug_engine.js"}return""}function nb(a){return"/javascript/ads/formats/mysidia/designs/"+(a+"_debug_bin.js")};function ob(){};var pb;function qb(){}C(qb,ob);function rb(a){a:{if(!a.a&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{new ActiveXObject(d);var e=a.a=d;break a}catch(f){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}e=a.a}return e?new ActiveXObject(e):new XMLHttpRequest}pb=new qb;function sb(a,b){this.c=a;this.f=b;this.b=0;this.a=null}sb.prototype.get=function(){if(0<this.b){this.b--;var a=this.a;this.a=a.next;a.next=null}else a=this.c();return a};function tb(a,b){a.f(b);100>a.b&&(a.b++,b.next=a.a,a.a=b)};function ub(a){y.setTimeout(function(){throw a;},0)}var vb;
function wb(){var a=y.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&!G("Presto")&&(a=function(){var a=document.createElement("IFRAME");a.style.display="none";a.src="";document.documentElement.appendChild(a);var b=a.contentWindow;a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d="file:"==b.location.protocol?"*":b.location.protocol+"//"+b.location.host;a=B(function(a){if(("*"==d||a.origin==d)&&a.data==
c)this.port1.onmessage()},this);b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});if("undefined"!==typeof a&&!G("Trident")&&!G("MSIE")){var b=new a,c={},d=c;b.port1.onmessage=function(){if(void 0!==c.next){c=c.next;var a=c.I;c.I=null;a()}};return function(a){d.next={I:a};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof document&&"onreadystatechange"in document.createElement("SCRIPT")?function(a){var b=document.createElement("SCRIPT");
b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};document.documentElement.appendChild(b)}:function(a){y.setTimeout(a,0)}};function xb(){this.b=this.a=null}var zb=new sb(function(){return new yb},function(a){a.reset()});xb.prototype.add=function(a,b){var c=zb.get();c.set(a,b);this.b?this.b.next=c:this.a=c;this.b=c};function Ab(){var a=Bb,b=null;a.a&&(b=a.a,a.a=a.a.next,a.a||(a.b=null),b.next=null);return b}function yb(){this.next=this.b=this.a=null}yb.prototype.set=function(a,b){this.a=a;this.b=b;this.next=null};yb.prototype.reset=function(){this.next=this.b=this.a=null};function Cb(a,b){Db||Eb();Fb||(Db(),Fb=!0);Bb.add(a,b)}var Db;function Eb(){if(y.Promise&&y.Promise.resolve){var a=y.Promise.resolve(void 0);Db=function(){a.then(Gb)}}else Db=function(){var a=Gb;!A(y.setImmediate)||y.Window&&y.Window.prototype&&!G("Edge")&&y.Window.prototype.setImmediate==y.setImmediate?(vb||(vb=wb()),vb(a)):y.setImmediate(a)}}var Fb=!1,Bb=new xb;function Gb(){for(var a;a=Ab();){try{a.a.call(a.b)}catch(b){ub(b)}tb(zb,a)}Fb=!1};function T(a){this.a=0;this.j=void 0;this.f=this.b=this.c=null;this.g=this.i=!1;if(a!=z)try{var b=this;a.call(void 0,function(a){U(b,2,a)},function(a){U(b,3,a)})}catch(c){U(this,3,c)}}function Hb(){this.next=this.c=this.b=this.f=this.a=null;this.g=!1}Hb.prototype.reset=function(){this.c=this.b=this.f=this.a=null;this.g=!1};var Ib=new sb(function(){return new Hb},function(a){a.reset()});function Jb(a,b,c){var d=Ib.get();d.f=a;d.b=b;d.c=c;return d}
T.prototype.then=function(a,b,c){return Kb(this,A(a)?a:null,A(b)?b:null,c)};T.prototype.then=T.prototype.then;T.prototype.$goog_Thenable=!0;function Lb(a,b){return Kb(a,null,b,void 0)}T.prototype.cancel=function(a){0==this.a&&Cb(function(){var b=new V(a);Mb(this,b)},this)};
function Mb(a,b){if(0==a.a)if(a.c){var c=a.c;if(c.b){for(var d=0,e=null,f=null,g=c.b;g&&(g.g||(d++,g.a==a&&(e=g),!(e&&1<d)));g=g.next)e||(f=g);e&&(0==c.a&&1==d?Mb(c,b):(f?(d=f,d.next==c.f&&(c.f=d),d.next=d.next.next):Nb(c),Ob(c,e,3,b)))}a.c=null}else U(a,3,b)}function Pb(a,b){a.b||2!=a.a&&3!=a.a||Qb(a);a.f?a.f.next=b:a.b=b;a.f=b}
function Kb(a,b,c,d){var e=Jb(null,null,null);e.a=new T(function(a,g){e.f=b?function(c){try{var e=b.call(d,c);a(e)}catch(k){g(k)}}:a;e.b=c?function(b){try{var e=c.call(d,b);void 0===e&&b instanceof V?g(b):a(e)}catch(k){g(k)}}:g});e.a.c=a;Pb(a,e);return e.a}T.prototype.s=function(a){this.a=0;U(this,2,a)};T.prototype.u=function(a){this.a=0;U(this,3,a)};
function U(a,b,c){if(0==a.a){a===c&&(b=3,c=new TypeError("Promise cannot resolve to itself"));a.a=1;a:{var d=c,e=a.s,f=a.u;if(d instanceof T){Pb(d,Jb(e||z,f||null,a));var g=!0}else{if(d)try{var h=!!d.$goog_Thenable}catch(k){h=!1}else h=!1;if(h)d.then(e,f,a),g=!0;else{h=typeof d;if("object"==h&&null!=d||"function"==h)try{var n=d.then;if(A(n)){Rb(d,n,e,f,a);g=!0;break a}}catch(k){f.call(a,k);g=!0;break a}g=!1}}}g||(a.j=c,a.a=b,a.c=null,Qb(a),3!=b||c instanceof V||Sb(a,c))}}
function Rb(a,b,c,d,e){function f(a){h||(h=!0,d.call(e,a))}function g(a){h||(h=!0,c.call(e,a))}var h=!1;try{b.call(a,g,f)}catch(n){f(n)}}function Qb(a){a.i||(a.i=!0,Cb(a.o,a))}function Nb(a){var b=null;a.b&&(b=a.b,a.b=b.next,b.next=null);a.b||(a.f=null);return b}T.prototype.o=function(){for(var a;a=Nb(this);)Ob(this,a,this.a,this.j);this.i=!1};
function Ob(a,b,c,d){if(3==c&&b.b&&!b.g)for(;a&&a.g;a=a.c)a.g=!1;if(b.a)b.a.c=null,Tb(b,c,d);else try{b.g?b.f.call(b.c):Tb(b,c,d)}catch(e){Ub.call(null,e)}tb(Ib,b)}function Tb(a,b,c){2==b?a.f.call(a.c,c):a.b&&a.b.call(a.c,c)}function Sb(a,b){a.g=!0;Cb(function(){a.g&&Ub.call(null,b)})}var Ub=ub;function V(a){E.call(this,a)}C(V,E);V.prototype.name="cancel";var Vb=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#([\s\S]*))?$/;function Wb(){return Xb("GET","/javascript/ads/formats/mysidia/designs/design_metadata_map_jspb.jspb",null).then(function(a){return JSON.parse(a.responseText)})}function Yb(a){return Xb("POST","",a).then(function(a){return JSON.parse(a.responseText)})}
function Xb(a,b,c){var d={},e=d.la?rb(d.la):rb(pb);return Lb(new T(function(f,g){var h;try{e.open(a,b,!0)}catch(l){g(new W("Error opening XHR: "+l.message,b,e))}e.onreadystatechange=function(){if(4==e.readyState){y.clearTimeout(h);a:switch(e.status){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var a=!0;break a;default:a=!1}!a&&(a=0===e.status)&&(a=b.match(Vb)[1]||null,!a&&y.self&&y.self.location&&(a=y.self.location.protocol,a=a.substr(0,a.length-1)),a=a?a.toLowerCase():"",a=!("http"==
a||"https"==a||""==a));a?f(e):g(new Zb(e.status,b,e))}};e.onerror=function(){g(new W("Network error",b,e))};if(d.headers){for(var n in d.headers){var k=d.headers[n];null!=k&&e.setRequestHeader(n,k)}k=d.headers["Content-Type"]}n=y.FormData&&c instanceof y.FormData;"POST"!=a||void 0!==k||n||e.setRequestHeader("Content-Type","application/x-www-form-urlencoded;charset=utf-8");d.withCredentials&&(e.withCredentials=d.withCredentials);d.responseType&&(e.responseType=d.responseType);d.mimeType&&e.overrideMimeType(d.mimeType);
0<d.ka&&(h=y.setTimeout(function(){e.onreadystatechange=z;e.abort();g(new $b(b,e))},d.ka));try{e.send(c)}catch(l){e.onreadystatechange=z,y.clearTimeout(h),g(new W("Error sending XHR: "+l.message,b,e))}}),function(a){a instanceof V&&e.abort();throw a;})}function W(a,b,c){E.call(this,a+", url="+b);this.url=b;this.D=c}C(W,E);W.prototype.name="XhrError";function Zb(a,b,c){W.call(this,"Request Failed, status="+a,b,c);this.status=a}C(Zb,W);Zb.prototype.name="XhrHttpError";
function $b(a,b){W.call(this,"Request timed out",a,b)}C($b,W);$b.prototype.name="XhrTimeoutError";function ac(a){try{var b;if(b=!!a&&null!=a.location.href)a:{try{pa(a.foo);b=!0;break a}catch(c){}b=!1}return b}catch(c){return!1}};var bc=ua||va||H&&Ba(11)||ta;function cc(a,b){if(dc)a.srcdoc=b;else if(bc){if(a=a.contentWindow)a=a.document,a.open("text/html","replace"),a.write(b),a.close()}else ec(a,b)}var dc=va&&"srcdoc"in document.createElement("IFRAME");function ec(a,b){function c(){var c=a.contentWindow;c&&(c.goog_content=b,c.location.replace("javascript:window.goog_content"))}H&&Ba(7)&&!Ba(10)&&6>fc()&&gc(b)&&(b=hc(b));var d;if(d=H){try{var e=ac(a.contentWindow)}catch(f){e=!1}d=!e}d?ic(a,c):c()}
function fc(){var a=navigator.userAgent.match(/Trident\/([0-9]+.[0-9]+)/);return a?parseFloat(a[1]):0}var jc=0;function ic(a,b){var c="goog_rendering_callback"+jc++;y[c]=b;a.src="javascript:'<script>(function() {document.domain = \""+document.domain+'";var continuation = window.parent.'+c+";window.parent."+c+" = null;continuation();})()\x3c/script>'"}function gc(a){for(var b=0;b<a.length;++b)if(127<a.charCodeAt(b))return!0;return!1}
function hc(a){a=unescape(encodeURIComponent(a));for(var b=Math.floor(a.length/2),c=[],d=0;d<b;++d)c[d]=String.fromCharCode(256*a.charCodeAt(2*d+1)+a.charCodeAt(2*d));1==a.length%2&&(c[b]=a.charAt(a.length-1));return c.join("")};function kc(a,b){cb(a);b=u(b);for(var c=b.next();!c.done;c=b.next())c=c.value,a.appendChild(new Option(c,c))}function lc(a){a.currentTarget.parentNode.querySelector("textarea").classList.toggle("hidden")}
function mc(){this.S=R("#ad-js-path");this.Y=R("#pure-client");this.ca=R("#server");this.ba=R("#server-adjuster");this.Z=R("#prod-pure-client");this.aa=R("#prod-server");this.$=R("#prod-server-adjuster");this.V=R("#canary-pure-client");this.X=R("#canary-server");this.W=R("#canary-server-adjuster");this.c=R("#design");this.a=R("#layout");this.T=R("#variant");this.f=R("#prod-design");this.s=R("#tool-background-color");this.A="";this.F=[];this.i=[];this.g="preserved";this.U=this.o=0;this.B=[];this.j=
this.u="";this.b=new Map;nc(this)}function oc(){return Lb(Wb().then(function(a){a=new Za(a);return Array.from(Ea(Ja(a,1,Oa)),function(a){return a[0]})}),function(){console.error("Design metadata file failed to load!");return[]})}m=mc.prototype;
m.ha=function(a,b,c){var d=document.importNode(R("#debug_node_server_info_item").content.querySelector("div"),!0),e=d.querySelector("div");e.querySelector("span").innerText=b;S("click",e,lc);d.querySelector("textarea").value=c;"Choice"==b&&d.querySelector(".optional_debug_div").appendChild(pc(a));return d};
function pc(a){var b=document.importNode(R("#manual_node_debug").content.querySelector("div"),!0),c=b.querySelector("input");S("click",b.querySelector("button"),function(){window.postMessage(JSON.stringify({id:a,node:parseInt(c.value,10),content:"",tag:""}),window.location.origin)});return b}function qc(a,b){a.b.has(b)||a.b.set(b,{J:null,w:null,O:null,N:null,H:null,G:null,M:null,K:null});return a.b.get(b)}
function rc(a,b,c,d,e,f,g){var h=document.importNode(R("#preview_item").content.querySelector("div"),!0),n=h.querySelector(".rendering-info-header .header-text");n.innerText=e+" x "+f+" "+b;var k=h.querySelector(".preview-iframe-wrapper .overlay-text");k.innerText=e+"px x "+f+"px";k.classList.toggle("hidden");var l=h.querySelector(".preview-iframe");l.width=e+"px";l.height=f+"px";l.id=c;l.setAttribute("data-stubby-version",d.tag?d.tag:"p");cc(l,g);S("load",l,function(){S("resize",l.contentWindow,
function(){k.innerText=l.style.width+" x "+l.style.height})});f=h.querySelector(".debug-info");f.querySelector("span").innerText=d.name;var q=f.querySelector("div");q.id=c+"-con";q.style.display="none";q.style.width=e+"px";S("click",h.querySelector(".rendering-info-header .close-preview"),function(){h.parentNode.removeChild(h)});S("click",h.querySelector(".rendering-info-header .refresh-preview"),function(){cb(q);l.classList.remove("resize");k.classList.add("hidden");var d=l.style&&l.style.width?
l.style.width:l.getAttribute("width"),e=l.style&&l.style.height?l.style.height:l.getAttribute("height"),f=qc(a,c);f=window.mys.preview.getPreviewHtml(f.O,f.N,f.H,f.M,f.w?f.w.m():null,f.K,parseInt(d,10),parseInt(e,10),"","",f.G,c);cc(l,f);n.innerText=d+" x "+e+" "+b});S("click",h.querySelector(".rendering-info-header .resize-preview"),function(){l.classList.add("resize");l.contentDocument.body.style.opacity=.2;k.classList.toggle("hidden")});return h}
function sc(a,b,c,d,e,f,g,h,n,k){d=u(d);for(var l=d.next();!l.done;l=d.next()){l=l.value;a.U++;var q=[];a.Y.checked&&q.push(db);a.ca.checked&&q.push(eb);a.ba.checked&&q.push(fb);a.Z.checked&&q.push(gb);a.aa.checked&&q.push(hb);a.$.checked&&q.push(ib);a.V.checked&&q.push(jb);a.X.checked&&q.push(kb);a.W.checked&&q.push(lb);q=u(q);for(var D=q.next();!D.done;D=q.next()){var x=D.value,ia="p-"+a.U+"-"+x.value;D=mb(x,a.u,a.j);if(x==fb||x==ib){var I=Object.assign({},e);I=Object.assign(I,{disable_adjuster:!1})}else I=
e;var wc=window.mys.preview.getPreviewHtml(D,h,f,g,n?n.m():null,I,l[0],l[1],"","",k,ia);c.appendChild(rc(a,b,ia,x,l[0],l[1],wc));x=qc(a,ia);x.O=D;x.N=h;x.H=f;x.M=g;x.w=n;x.K=I;x.G=k}}}
function tc(a,b,c,d,e){var f=R("#ads-preview");if(f){var g={keep_last_variant:!0,disable_adjuster:!0,fill_client_view_debug_message:!0,is_rtl:R("#is-rtl").checked,is_amp:R("#is-amp").checked},h=R("#overlay-client-view").checked,n=R("#show-rendering-data").checked;g.output_client_view=h;g.output_rendering_data=n;g.enable_debug_addon=h||n;"WINNER"!=c&&(g.force_layout=c,h=parseInt(d,10),isNaN(h)||(g.force_variant=h));var k="",l=[];"preserved"==a.g?k=a.A:"fromrr"==a.g?l=a.F:"fromri"==a.g&&(l=a.i);var q=
[b,c,d].join(" "),D=a.f.checked?"http://pagead2.googlesyndication.com/pagead/gadgets/mysidia/"+("design/"+b+".js"):nb(b);a.f.checked?sc(a,q,f,e,g,k,a.o,D,null,l):uc(b).then(function(b){sc(a,q,f,e,g,k,a.o,D,b,l)})}}m.R=function(){this.A=this.S.value+".js"};
function vc(a){R("#hint-text-rr").innerText="Loading...";var b=R("#rr-input").value.replace(/\r?\n?/g,""),c=R("#rendering-server-host").value,d=new FormData;d.append("rr",b.trim());d.append("rs",c);Lb(Yb(d).then(function(b){R("#hint-text-rr").innerText="Loaded";a.F=b;console.log(JSON.stringify(b))}),function(a){var b="Didn't get useful data.";a&&a.D&&a.D.responseText&&(b+=" Error message: "+a.D.responseText);R("#hint-text-rr").innerText=b})}
m.P=function(a){a&&this.o++;a=[];for(var b=u(R("#ad-slots").value.split(",")),c=b.next();!c.done;c=b.next()){var d=c.value.split("x");2==d.length&&(c=parseInt(d[0],10),d=parseInt(d[1],10),isNaN(c)||isNaN(d)||a.push([c,d]))}tc(this,this.c.value,this.a.value,this.T.value,a)};
function uc(a){return new Promise(function(b){var c=R("#design_template");c.src="/javascript/ads/formats/mysidia/designs/"+(a+".html");c.onload=function(){console.log("Loaded design "+a);var d=c.contentDocument,e=d.createElement("script"),f=window.mys.specs.analyze(d);S("load",e,function(){var a=c.contentWindow.mys.design.modifyDesignSpec(d.head,d.body,f);b(new Ta(a))});e.setAttribute("src",nb(a));d.body.appendChild(e)}})}m.fa=function(){uc(this.c.value).then(this.ea.bind(this))};
m.ea=function(a){var b=["WINNER"];a=u(Q(a,Va,2));for(var c=a.next();!c.done;c=a.next())b.push(P(c.value,1,""));kc(this.a,b);this.L()};m.L=function(){uc(this.c.value).then(this.ga.bind(this))};m.ga=function(a){var b=this;if(this.a.value){var c=["WINNER"];if(a=Q(a,Va,2).find(function(a){return P(a,1,"")===b.a.value})){a=Q(a,Xa,4).length;for(var d=0;d<a;++d)c.push(d)}kc(this.T,c)}};
m.C=function(a,b){bb(".tabcontent").forEach(function(a){a.classList.add("hidden")});bb(".tablink").forEach(function(a){a.classList.remove("active")});R("#"+a).classList.remove("hidden");b.currentTarget.classList.add("active");this.g=a};m.da=function(){cb(R("#ads-preview"));this.b.clear()};
m.ia=function(a){a=a.data;if("string"===typeof a){var b=null;try{b=JSON.parse(a)}catch(q){console.warn("Could not parse message: "+a)}if(b){a=b.id;var c=R("#"+a+"-con"),d=[];c.style.display="block";if(0>b.node){var e="",f="";if("clientview_msg"===b.tag){b=Na(Pa,b.content);var g=qc(this,a);g.J=b;f=P(b,2,"");e=P(b,3,0);if(g=g.w){g=u(Q(g,Va,2));for(var h=g.next();!h.done;h=g.next())if(h=h.value,P(h,1,"")===f){var n=Q(h,Xa,4).length;if(n<=e)console.error("Mismatch: variant count "+n+" smaller than variant index "+
e);else{var k=Q(h,Xa,4)[e];var l=P(k,1,0);k=Ea(Ja(k,3,null)).map(function(a){return a[0]+":"+a[1]}).join(", ")}}}else console.error("design data not found.");e="layout: "+f+"\nvariant index (0-index): "+e+"\nvariant count: "+n+"\nscore: "+ +P(b,6,0)+"\nrejected: "+P(b,5,!1)+"\nvariant priority: "+l+"\nvariableMap: "+k;f="Choice"}else"renderingdata_msg"===b.tag&&(n=Na($a,b.content),f="Rendering Data",e="Map:\n"+Ea(Ja(n,2,null)).map(function(a){return a[0]+":"+a[1]}).join("\n"));d.push([f,e])}else{l=
qc(this,a).J;if(!l){console.error("client view not found.");return}n=b.node;k=Q(l,Ra,1).length;if(k<=n)console.error("Mismatch: client node count "+k+" smaller than given client node index "+n);else for(l=u(Q(l,Ra,1)),k=l.next();!k.done;k=l.next())k=k.value,P(k,3,0)===n&&(null!=Ia(k,9)?(k=Ka(k),d.push(["Box for node "+n,P(k,1,"")]),d.push(["BoxResult for node "+n,P(k,2,"")])):d.push(["debug info for node "+n,"<not available>"]))}d=u(d);for(n=d.next();!n.done;n=d.next())c.appendChild(this.ha.apply(this,
[a].concat(ea(n.value))))}}};m.ja=function(){R("body").style.backgroundColor=this.s.value};
function xc(a){(new Map([["#preserved-button",a.C.bind(a,"preserved")],["#fromrr-button",a.C.bind(a,"fromrr")],["#fromri-button",a.C.bind(a,"fromri")],["#render-button-next",a.P.bind(a,!0)],["#render-button-current",a.P.bind(a,!1)],["#clear-button",a.da.bind(a)],["#rr-input-button",function(){vc(a)}],["#ri-input-button",function(){try{a.i=JSON.parse(R("#ri-input").value.replace(/\r?\n?/g,"")),R("#hint-text-ri").innerText="Ready to use",console.log(a.i)}catch(b){a.i=[],R("#hint-text-ri").innerText=
"Error:"+b}}]])).forEach(function(a,c){S("click",R(c),a)});S("change",a.f,function(){bb(".local").forEach(function(a){a.classList.toggle("hidden")});yc(a)});S("change",a.S,a.R.bind(a));S("change",a.a,a.L.bind(a));S("change",a.s,a.ja.bind(a));S("focusout",a.c,a.fa.bind(a));S("message",window,a.ia.bind(a))}function yc(a){a.f.checked?cb(R("#design-name-list")):kc(R("#design-name-list"),a.B)}
function nc(a){xc(a);a.s.value="#fff";oc().then(function(b){a.B=b;yc(a)});var b=window.MysidiaEngineVersions;b&&2==b.length?(a.u=b[0],R("#prod-eng-version").innerText=a.u,a.j=b[1],R("#canary-eng-version").innerText=a.j):console.error("mysidia_server_config is not available or has error.");R("#preserved-button").click();a.R();R("#render-button-next").removeAttribute("disabled");R("#render-button-current").removeAttribute("disabled")}function zc(){S("DOMContentLoaded",document,function(){new mc})}
var X=["startPlay"],Y=y;X[0]in Y||"undefined"==typeof Y.execScript||Y.execScript("var "+X[0]);for(var Z;X.length&&(Z=X.shift());)X.length||void 0===zc?Y[Z]&&Y[Z]!==Object.prototype[Z]?Y=Y[Z]:Y=Y[Z]={}:Y[Z]=zc;}).call(this);
