var windowWidth=window.innerWidth;var windowHeight=window.innerHeight;function bannerHeight(){var headerH=jQuery(".header_sec").height();var homeBannerH=windowHeight-headerH;jQuery(".homeBanner").css('height',homeBannerH);}
function sticky_footer(){var page_height=jQuery('.wrapper').innerHeight();if(page_height<windowHeight){jQuery('.footer').addClass('sticky_footer');}else{jQuery('.footer').removeClass('sticky_footer');}}
jQuery(function(){jcf.replaceAll();});var indusArr=[];var categoryArr=[];function jobTaxArr(){var indusArr=[];var categoryArr=[];if(jQuery('.showAll').length){jQuery("body").on("click",".showAll a",function(e){if(jQuery(this).attr('data-tax')=='industry'){var $indusArray2=siteVars.indusArray2;jQuery.each($indusArray2,function(index,item){var indusArrStr=' <li>  <input type="checkbox" id="chk_'+index+'" name="industry_type" value="'+index+'"/>      <label title="Unchecked state" for="chk_'+index+'">'+item+'</label></li>';indusArr.push(indusArrStr);console.log(indusArr);});jQuery('.filterField.industry_type ul').append(indusArr);jQuery(this).parents('.showAll').hide();}
if(jQuery(this).attr('data-tax')=='category'){var $categoryArray2=siteVars.categoryArray2;jQuery.each($categoryArray2,function(index,item){var catArrStr=' <li>  <input type="checkbox" id="chkCat_'+index+'" name="category_type" value="'+index+'"/>      <label title="Unchecked state" for="chkCat_'+index+'">'+item+'</label></li>';categoryArr.push(catArrStr);console.log(categoryArr);});jQuery('.filterField.category_type ul').append(categoryArr);jQuery(this).parents('.showAll').hide();}
jcf.replaceAll();});}}
jQuery(document).ready(function(){windowHeight=window.innerHeight;jQuery('.svgIcon').each(function(){var $img=jQuery(this);var imgID=$img.attr('id');var imgClass=$img.attr('class');var imgURL=$img.attr('src');jQuery.get(imgURL,function(data){var $svg=jQuery(data).find('svg');if(typeof imgID!=='undefined'){$svg=$svg.attr('id',imgID);}
if(typeof imgClass!=='undefined'){$svg=$svg.attr('class',imgClass+' replaced-svg');}
$svg=$svg.removeAttr('xmlns:a');$img.replaceWith($svg);},'xml');});if(navigator.userAgent.indexOf('Mac OS X')!=-1){jQuery("body").addClass("mac");}else{jQuery("body").addClass("pc");}
if(navigator.userAgent.match(/(iPhone|Android|BlackBerry|iPod|iPad)/)){}else{jQuery('a[href^=tel]').click(function(e){e.preventDefault();});}
jQuery('.fancybox').fancybox({wrapCSS:'loginPopup',width:370,padding:0,beforeLoad:function(){}});jQuery('.fancybox').fancybox({wrapCSS:'signupPopup',width:370,padding:0,beforeLoad:function(){}});if(jQuery('.regForm').length){if(siteVars.providerName=='Facebook'||siteVars.providerName=='Linkedin'){jQuery(this).find('.user_email').removeClass('showField');jQuery(this).find('.user_email').addClass('hideField');}
else if(siteVars.providerName=='Twitter'){jQuery(this).find('.user_email').removeClass('hideField');jQuery(this).find('.user_email').addClass('showField');jQuery(this).find('.user_email').children('.ginput_container').find('input').val('');jQuery(this).find('.user_email').children('.ginput_container').find('input').attr('placeholder','');}
else{jQuery(this).find('.user_email').removeClass('hideField');jQuery(this).find('.user_email').addClass('showField');}}
jQuery(document).bind('gform_confirmation_loaded',function(event,formId){var formId=formId;var providerName=siteVars.providerName;console.log(formId);console.log(providerName);jQuery.ajax({type:"POST",dataType:'json',url:siteVars.ajaxURL,success:function(resultProp){resultProp.meta;resultProp.emailMsg;resultProp.msgConfirm;},data:{'action':'reg_confirmation','formId':formId,'providerName':providerName}});});jQuery('.applyJobBtn').click(function(e){e.preventDefault();var load_gif="<div class=\"loadGif\" style=\"display: inline-block;\"></div>";var resultProp='';var $this=jQuery(this);var jobId=jQuery(this).attr('data-postid');var candidateid=jQuery(this).attr('data-candidateid');var companyid=jQuery(this).attr('data-companyid');jQuery(this).parents('.job-description').find('.succesMsg')
jQuery(this).parents('.job-description').find('.applybtn-large').append(load_gif);jQuery.ajax({url:siteVars.ajaxURL,type:'post',dataType:'json',data:{'action':'applyForJob','candidateid':candidateid,'companyid':companyid,'jobId':jobId,},success:function(resultProp){jQuery('.applyJobBtn').parents('.job-description').find('.loadGif').remove();if(resultProp.status=='success'){resultProp.test;jQuery('.applybtn-large').html(resultProp.BtnHtml);jQuery('.topBarNote').html(resultProp.successMsg).fadeIn(500);setTimeout(function(){jQuery('.topBarNote').fadeOut(500);},3000);setTimeout(function(){jQuery('.topBarNote').empty();},4000);}
else{}}});});jQuery('.applyBtnFirst').click(function(e){var jobPostId=jQuery(this).attr('data-postid');jQuery.ajax({url:siteVars.ajaxURL,type:'post',dataType:'json',data:{'action':'applyForJobFirst','jobPostId':jobPostId,},success:function(resultProp){if(resultProp.status=='success'){resultProp.test;}}});});jQuery('.simJobsSingle').click(function(e){e.preventDefault();var similarJobSingle=jQuery(this).parents('.single-job').find('.similarJobSingle').offset().top;jQuery("html, body").animate({scrollTop:similarJobSingle},'2000');})
if(jQuery("#Mobile_menu").length>0){jQuery('nav#Mobile_menu').mmenu({offCanvas:{position:"right",zposition:"front"}});var API=jQuery("nav#Mobile_menu").data("mmenu");jQuery(".close_m_menu").click(function(){API.close();});}
jQuery('#loginCompany, #loginCompany input').bind('change submit',function(e){var pass=true;jQuery('.required_c_l').each(function(e1){if(jQuery(this).val()==null||jQuery(this).val()==''||jQuery(this).val()==' '){jQuery(this).css({'border':'1px solid red'});pass=false;}else{jQuery(this).css({'border':'1px solid #ccc'});}})
if(e.type=='submit'){if(pass==false){e.preventDefault();}
else{var regloading=jQuery('#loginCompany .reg_login_loading');regloading.css('visibility','visible');jQuery.ajax({type:'POST',dataType:'json',url:siteVars.ajaxURL,data:{'action':'custom_login','user_login':encodeURIComponent(jQuery("#loginCompany input[name='user_email']").val()),'user_password':encodeURIComponent(jQuery("#loginCompany input[name='user_password']").val()),'login_form':'company_login_form'},beforeSend:function(){regloading.css('visibility','visible');},success:function(result){regloading.css('visibility','hidden');if(result.status==0){jQuery('#loginCompany').siblings("#ajaxResponse1").html(result.msg);}
else if(result.status==2){console.log(result);jQuery('.fancybox-close').trigger('click');jQuery('.topBarNote').html(result.msg).fadeIn(500);setTimeout(function(){jQuery('.topBarNote').fadeOut(500);},3000);setTimeout(function(){jQuery('.topBarNote').empty();location.reload(true);},4000);}else{window.location=result.redirect}}})
e.preventDefault();}}});jQuery('#login_mail, #login_mail input').bind('change submit',function(e){var pass=true;jQuery('.required').each(function(e1){if(jQuery(this).val()==null||jQuery(this).val()==''||jQuery(this).val()==' '){jQuery(this).css({'border':'1px solid red'});pass=false;}else{jQuery(this).css({'border':'1px solid #ccc'});}})
if(e.type=='submit'){if(pass==false){e.preventDefault();}
else{var rememberA;var regloading=jQuery('#login_mail .reg_login_loading');var checkval=jQuery("#login_mail input[name='user_remember']");rememberA=checkval.is(':checked')?1:0;regloading.css('visibility','visible');jQuery.ajax({type:'POST',dataType:'json',url:siteVars.ajaxURL,data:{'action':'custom_login','user_login':encodeURIComponent(jQuery("#login_mail input[name='user_login']").val()),'user_password':encodeURIComponent(jQuery("#login_mail input[name='user_password']").val()),'rememberA':rememberA,'login_form':'login_form'},beforeSend:function(){regloading.css('visibility','visible');},success:function(result){regloading.css('visibility','hidden');if(result.status==0){jQuery('#login_mail').siblings("#ajaxResponse1").html(result.msg);}
else if(result.status==2){console.log(result);jQuery('.fancybox-close').trigger('click');jQuery('.topBarNote').html(result.msg).fadeIn(500);setTimeout(function(){jQuery('.topBarNote').fadeOut(500);},3000);setTimeout(function(){jQuery('.topBarNote').empty();location.reload(true);},4000);}
else if(result.status==1){location.reload(true);}else{jQuery('.login-button a').trigger('click');jQuery("#ajaxResponse1").html(result.msg);jQuery("#login_mail").remove();jQuery("#ajaxResponse1").append('<p>You will be redirected automatically in 3 sec.</p>');setTimeout(window.location=result.redirect,3000)}}})
e.preventDefault();}}})
jQuery('#signupCompany, #signupCompany input').bind('change submit',function(e){var pass=true;jQuery('.requiredC').each(function(e1){if(jQuery(this).val()==null||jQuery(this).val()==''||jQuery(this).val()==' '){jQuery(this).css({'border':'1px solid red'});pass=false;}else{jQuery(this).css({'border':'1px solid #ccc'});}})
if(e.type=='submit'){if(pass==false){e.preventDefault();}
else{var rememberA;var regloading=jQuery('#signupCompany .reg_login_loading');var checkval=jQuery("#signupCompany input[name='user_remember']");rememberA=checkval.is(':checked')?1:0;regloading.css('visibility','visible');jQuery.ajax({type:'POST',dataType:'json',url:siteVars.ajaxURL,data:{'action':'custom_login','user_login':encodeURIComponent(jQuery("#signupCompany input[name='user_login']").val()),'user_password':encodeURIComponent(jQuery("#signupCompany input[name='user_password']").val()),'user_phone':encodeURIComponent(jQuery("#signupCompany input[name='user_phone']").val()),'rememberA':rememberA,'email':jQuery("#signupCompany input[name='user_email']").val(),'company_signup':'company_signup'},beforeSend:function(){regloading.css('visibility','visible');},success:function(result){regloading.css('visibility','hidden');if(result.status==0){console.log(result);jQuery('#signupCompany').siblings("#ajaxResponse1").html(result.msg);}else{jQuery('.fancybox-close').trigger('click');jQuery('.topBarNote').html(result.msg).fadeIn(500);setTimeout(function(){jQuery('.topBarNote').fadeOut(500);},3000);setTimeout(function(){jQuery('.topBarNote').empty();window.location=result.redirect},4000);}}})
e.preventDefault();}}})
if(jQuery(".tabs_main").length>0){jQuery(".tabs_main").find('.tabCont_div').removeClass('currentTabC');jQuery(".tabs_main").find('.current').addClass('currentTabC');jQuery('.tabs_main ul.tab_links li a').on('click',function(event){jQuery(".tabs_main").find('.tabCont_div').removeClass('currentTabC');event.preventDefault();var $this=jQuery(this).closest('.tabs_main');var hrefID=this.hash.substr(1);jQuery($this).find('ul.tab_links li a').removeClass('tab-active');jQuery(this).addClass('tab-active');jQuery($this).find('.tabCont_div').hide();jQuery($this).find('#'+hrefID).show();jQuery($this).find('#'+hrefID).addClass('currentTabC');});}
jQuery('.tab1OuterBtn').click(function(e){e.preventDefault();var $this=jQuery(this);$this.fadeOut(400);setTimeout(function(){$this.next('.tabContentOuter').fadeIn(400);},500);});var clickEventType=((document.ontouchstart!==null)?'click':'touchstart');jQuery("body").on("click",".open_submenu",function(e){var $this=jQuery(this);$this.children(".sub-menu").slideToggle();});jQuery("body").on(clickEventType,".noti_job_name",function(e){var $this=jQuery(this);if($this.hasClass('opened')){$this.removeClass('opened')
$this.next(".noti_job_expand").slideUp();}
else{$this.addClass('opened');$this.next(".noti_job_expand").slideDown();}});jQuery("body").on(clickEventType,".noti_head",function(e){var notification_count=parseInt(jQuery('.numJobAlert').text());var $this=jQuery(this);var notiParent=jQuery(this).parent(".noti_sing");if(notiParent.hasClass('noti_unread')){if($this.hasClass('sidebar')){var sidebar='1';}
else{var sidebar='0';}
var notiID=$this.attr("data-noti-id");var notiExtParentCount=jQuery(this).parents(".noti_box").children(".noti_job_name").children("span");notiParent.removeClass('noti_unread');$this.addClass('opened');$this.next(".noti_expand").slideDown();jQuery.ajax({type:'POST',url:siteVars.ajaxURL,data:{'action':'update_ajax_notification','notiID':notiID},success:function(result){if(result=='notification read'){console.log(result);if(notiExtParentCount.attr("data-count")>1){console.log(notiExtParentCount.attr("data-count"));var countValue=notiExtParentCount.attr("data-count")-1;console.log(countValue);notiExtParentCount.attr("data-count",countValue);notiExtParentCount.html("+"+countValue);}else if(notiExtParentCount.attr("data-count")=='1'){notiExtParentCount.remove();}
if(sidebar=='1'){$this.append('<i class="float_right fa fa-check"></i>');}
if(notification_count>1){notification_count=notification_count-1;jQuery('.numJobAlert').text(notification_count);console.log('new notification_count = '+notification_count);}}}})}
else{if($this.hasClass('opened')){$this.removeClass('opened')
$this.next(".noti_expand").slideUp();}
else{$this.addClass('opened');$this.next(".noti_expand").slideDown();}}});jQuery("body").on(clickEventType,"input.working_still",function(){var $this=jQuery(this);var expParentBox=$this.parents(".js_expSec");var endMonthElem=expParentBox.find(".end_month");var endYearElem=expParentBox.find(".end_year");if(jQuery(this).is(':checked')){jcf.destroy(endMonthElem);jcf.destroy(endYearElem);endMonthElem.prop('selectedIndex',0);endYearElem.prop('selectedIndex',0);jcf.replace(endMonthElem);jcf.replace(endYearElem);endMonthElem.parent(".ginput_container").addClass("selectDisabled");endYearElem.parent(".ginput_container").addClass("selectDisabled");}else{endMonthElem.parent(".ginput_container").removeClass("selectDisabled");endYearElem.parent(".ginput_container").removeClass("selectDisabled");}});jQuery("body").on(clickEventType,"input.studying_still",function(){var $this=jQuery(this);var expParentBox=$this.parents(".js_eduSec");var endMonthElem=expParentBox.find(".end_month");var endYearElem=expParentBox.find(".end_year");if(jQuery(this).is(':checked')){jcf.destroy(endMonthElem);jcf.destroy(endYearElem);endMonthElem.prop('selectedIndex',0);endYearElem.prop('selectedIndex',0);jcf.replace(endMonthElem);jcf.replace(endYearElem);endMonthElem.parent(".ginput_container").addClass("selectDisabled");endYearElem.parent(".ginput_container").addClass("selectDisabled");}else{endMonthElem.parent(".ginput_container").removeClass("selectDisabled");endYearElem.parent(".ginput_container").removeClass("selectDisabled");}});});jQuery(window).load(function(){windowHeight=window.innerHeight;jobTaxArr();sticky_footer();check_for_email();fire_ajax_for_post_count();password_slide();candidate_account_settings();candidate_account_settings_form_submit();});function candidate_account_settings_form_submit(){jQuery(document).on("focusout",".edit_candidate_settings #pass1, .edit_candidate_settings #pass2",function(){var pass1=jQuery('.edit_candidate_settings').find('input#pass1').val();var pass2=jQuery('.edit_candidate_settings').find('input#pass2').val();console.log('email = '+document.getElementById("email").value);if(pass1!=pass2){jQuery('#all_fields_ok').val(0);console.log('no match');}
else{jQuery('#all_fields_ok').val(1);console.log('match');}});jQuery('#candidate_account_settings_form').submit(function(){if(jQuery('#all_fields_ok').val()=='0'){return false;}
if(jQuery('#email').val()==''){return false;}});}
function candidate_account_settings(){jQuery(document).on("change","#choose_industry",function(){var value=jQuery(this).val();jQuery('#ci').val(value);});jQuery(document).on("change","#choose_category",function(){var value=jQuery(this).val();jQuery('#cc').val(value);});jQuery(document).on("change","#choose_loc_job1",function(){var value=jQuery(this).val();jQuery('#clj1').val(value);});jQuery(document).on("change","#choose_indus_job1",function(){var value=jQuery(this).val();jQuery('#c1j1').val(value);});jQuery(document).on("change","#choose_cat_job1",function(){var value=jQuery(this).val();jQuery('#c1k1').val(value);});jQuery(document).on("change","#choose_loc_job2",function(){var value=jQuery(this).val();jQuery('#clj2').val(value);});jQuery(document).on("change","#choose_indus_job2",function(){var value=jQuery(this).val();jQuery('#c1k2').val(value);});jQuery(document).on("change","#choose_cat_job2",function(){var value=jQuery(this).val();jQuery('#c1l2').val(value);});jQuery(document).on("change","#choose_loc_job3",function(){var value=jQuery(this).val();jQuery('#clj3').val(value);});jQuery(document).on("change","#choose_indus_job3",function(){var value=jQuery(this).val();jQuery('#c1k3').val(value);});jQuery(document).on("change","#choose_cat_job3",function(){var value=jQuery(this).val();jQuery('#c1l3').val(value);});}
function password_slide(){jQuery(document).on("click","#change_password",function(){jQuery('.initial_hide').slideToggle();});}
function check_for_email(){jQuery(document).on("focusout",".check_email",function(){var email=jQuery(this).val();if(email==current_user_email){return false;}
jQuery('.no_show_check').hide();jQuery('.no_show_close').hide();jQuery.ajax({type:'POST',url:siteVars.ajaxURL,data:{'action':'check_for_email','email':email},success:function(response){response=JSON.parse(response);if(response['result']==1){jQuery('.no_show_check').show();jQuery('.no_show_close').hide();jQuery('#all_fields_ok').val(1);}
else{jQuery('.no_show_check').hide();jQuery('.no_show_close').show();jQuery('#all_fields_ok').val(0);}}})});}
function fire_ajax_for_post_count(){if(typeof current_job_postid!=='undefined'){var post_id=current_job_postid;jQuery.ajax({type:'POST',url:siteVars.ajaxURL,data:{'action':'increase_post_count','post_id':post_id},success:function(result){}})}}
jQuery(document).bind('gform_post_render',function(event,form){if(jQuery('.gForm_multiSelect').length){jQuery('.gForm_multiSelect').find('select').addClass('chosen-select');jQuery('.gForm_multiSelect').find('select').addClass('chosen-select jcf-ignore');}
jcf.replaceAll();jQuery('.svgIcon').each(function(){var $img=jQuery(this);var imgID=$img.attr('id');var imgClass=$img.attr('class');var imgURL=$img.attr('src');jQuery.get(imgURL,function(data){var $svg=jQuery(data).find('svg');if(typeof imgID!=='undefined'){$svg=$svg.attr('id',imgID);}
if(typeof imgClass!=='undefined'){$svg=$svg.attr('class',imgClass+' replaced-svg');}
$svg=$svg.removeAttr('xmlns:a');$img.replaceWith($svg);},'xml');});jQuery(".addRepeatBlock").click(function(e){var $this=jQuery(this);var repeatType=$this.attr('data-type');var dataShowNo=$this.attr('data-show');console.log(repeatType);console.log(dataShowNo);if(jQuery('.'+repeatType+'_'+dataShowNo).length){jQuery('.'+repeatType+'_'+dataShowNo).slideDown();$this.attr('data-show',parseInt(dataShowNo)+1);if(jQuery('.'+repeatType+'_'+(parseInt(dataShowNo)+1)).length){}else{$this.addClass('displayNone');}}
else{$this.addClass('displayNone');}});jQuery("body").on("click",".addSkills",function(e){var $this=jQuery(this);if(jQuery('.muitpleSkillsArea').length){jQuery('.muitpleSkillsArea').slideDown();$this.remove();}})});jQuery(window).resize(function(){windowWidth=window.innerWidth;windowHeight=window.innerHeight;sticky_footer();});if(jQuery('.chosen-select').length){var config={'.chosen-select':{},'.chosen-select-deselect':{allow_single_deselect:true},'.chosen-select-no-single':{disable_search_threshold:10},'.chosen-select-no-results':{no_results_text:'Oops, nothing found!'},'.chosen-select-width':{width:"95%"}}
for(var selector in config){jQuery(selector).chosen(config[selector]);}}
var userEmail;var resultProp;var load_gif="<div class=\"loadGif\" style=\"display: block;\"></div>";jQuery(document).on("focusout",".user_email  input",function(){var $this=jQuery(this);userEmail=jQuery(this).val();if(userEmail!=''){jQuery('.user_email').find('.ginput_container').append(load_gif);jQuery('.user_email').find('.emailExistMsg').remove();jQuery('.user_email').find('.msgText').remove();ajaxEmail();}});function ajaxEmail(){var resultProp;jQuery.ajax({type:"POST",dataType:'json',url:siteVars.ajaxURL,success:function(resultProp){jQuery('.user_email').find('.loadGif').remove();jQuery('.user_email').addClass('hello');jQuery('.user_email').find('.ginput_container').append(resultProp.msg);jQuery('.user_email').find('.ginput_container').append(resultProp.msgTestLine);if(resultProp.status!='failed'){jQuery('.user_email').parents('.regForm_wrapper').find('.gform_next_button').prop('disabled',false);}else{jQuery("#input_3_173").css({"border":"none;"});jQuery('.user_email').parents('.regForm_wrapper').find('.gform_next_button').prop('disabled','disabled');}},data:{'action':'email_exist','userEmail':userEmail,}});}
(function($){$(function(){$(".companySlider").owlCarousel({autoPlay:3000,navigation:true,navigationText:["<i class='fa fa-angle-left icon-white'></i>","<i class='fa fa-angle-right icon-white'></i>"],items:4,itemsDesktop:[1199,3],itemsDesktopSmall:[979,3]});$("div.lazy").lazyload({effect:"fadeIn"});jQuery("body").on("click",".jobTagCover .fa-close",function(e){$(this).parents('.searchInput1').find('.searchCover').css('display','none');$('.jobTagValue').val('');});jQuery("body").on("click",".jobLocCover .fa-close",function(e){$(this).parents('.searchInput1').find('.searchCover').css('display','none');$('.jobLocValue').val('');});$(".jobTagLabel").autocomplete({source:job_tags,focus:function(event,ui){$(".jobTagLabel").val(ui.item.label);return false;},select:function(event,ui){$(".jobTagLabel").val(ui.item.label);$(".jobTagValue").val(ui.item.id);$(".jobTagCover").css('display','block');$(".jobTagLabel").blur();return false;},search:function(event,ui){console.log(event);console.log(ui)}});$(".jobLocLabel").autocomplete({source:jobsLoc,select:function(event,ui){$(".jobLocLabel").val(ui.item.label);$(".jobLocValue").val(ui.item.id);$(".jobLocCover").css('display','block');$(".jobLocLabel").blur();return false;},search:function(event,ui){console.log(event);console.log(ui)}});$('.homeSearch').submit(function(){if($.trim($(".jobTagLabel").val())===""&&$.trim($(".jobLocLabel").val())===""){console.log('you did not fill out one of the fields');return false;}});jQuery('.emailLogin').click(function(e){if(jQuery('.signInForm').length){jQuery('.signInForm').slideToggle();}});});})(jQuery);jQuery(document).bind('gform_post_render',function(event,form){if(jQuery('.location_select').length>0){jQuery('.location_select select option').each(function(){var option_val=jQuery(this).html();if(option_val=='null'||option_val=='Location'){}
else{if(option_val.indexOf('- ')>=0){jQuery(this).addClass('child');}
else{jQuery(this).addClass('parent');}}});jcf.destroy('.location_select select');jQuery('.location_select select').addClass('selectRegion');jQuery('.location_select select').attr('data-jcf','{"multipleCompactStyle": true, "wrapNative": false, "wrapNativeOnMobile": false, "useCustomScroll": false}');jcf.replace('.location_select select');}
if(jQuery('.jcf_display').length>0){jQuery('.jcf_display select').each(function(){var selectID=jQuery(this).attr('id');jcf.destroy(jQuery(this));jQuery(this).attr('data-jcf','{"wrapNative": false, "wrapNativeOnMobile": false, "fakeDropInBody": false, "useCustomScroll": false}');jcf.replace(jQuery(this));});}
if(jQuery("li.gfield.cc_method").length>0){jQuery("li.gfield.cc_method").find("input[type='radio']").on("change",function(){var $this=jQuery(this);jQuery("li.gfield.cc_method").each(function(){var $sing=jQuery(this);var onclickVal=$sing.find("input[type='radio']").attr("onclick");if($sing.find("input[type='radio']").val()==$this.val()){$sing.find("input[type='radio']").attr("checked",true);if(typeof onclickVal!=='undefined'){onclickVal=onclickVal.split("(");var split_2=onclickVal[1].split("])");var formid_u=split_2[0].split(",[");var correctFormID=formid_u[0];var aba=JSON.parse('['+formid_u[1]+']');formid_u=formid_u[0];jQuery.each(aba,function(index,value){if(jQuery("li#field_"+correctFormID+"_"+value).length>0){jQuery("li#field_"+correctFormID+"_"+value).slideDown(400);}});}}else{$sing.find("input[type='radio']").attr("checked",false);$sing.find("input[type='radio']").parent("span").removeClass("jcf-checked").addClass("jcf-unchecked");if(typeof onclickVal!=='undefined'){onclickVal=onclickVal.split("(");var split_2=onclickVal[1].split("])");var formid_u=split_2[0].split(",[");var correctFormID=formid_u[0];var aba=JSON.parse('['+formid_u[1]+']');formid_u=formid_u[0];jQuery.each(aba,function(index,value){if(jQuery("li#field_"+correctFormID+"_"+value).length>0){jQuery("li#field_"+correctFormID+"_"+value).slideUp(400);}});}}})})}});jQuery(window).load(function(){newsletter_submit();custom_location_jcf();modify_year();});function modify_year(){if(jQuery('.year_modify').length>0){var d=new Date();var n=d.getFullYear();var next_year=n+1;var next_to_next_year=next_year+1;var years='<option value>Año</option><option value="'+n+'" selected>'+n+'</option><option value="'+next_year+'">'+next_year+'</option><option value="'+next_to_next_year+'">'+next_to_next_year+'</option>';jQuery('.year_modify .gfield_date_dropdown_year select').html(years);}}
function custom_location_jcf(){if(jQuery('.location_select').length>0){jQuery('.location_select select option').each(function(){var option_val=jQuery(this).html();if(option_val=='null'||option_val=='Location'){}
else{if(option_val.indexOf('- ')>=0){jQuery(this).html(option_val.replace('- ',''));jQuery(this).addClass('child');}
else{jQuery(this).addClass('parent');}}});jcf.destroy('.location_select select');jQuery('.location_select select').addClass('selectRegion');jQuery('.location_select select').attr('data-jcf','{"multipleCompactStyle": true, "wrapNative": false, "wrapNativeOnMobile": false, "useCustomScroll": false}');jcf.replace('.location_select select');}}
function newsletter_submit(){jQuery('.newsletter_form').submit(function(){var email=jQuery(this).find('input.oEmailId').val();if(!isValidEmailAddress(email)){console.log('invalid email');}
else{email_newsletter_submit(email,jQuery(this));}
return false;});}
function isValidEmailAddress(emailAddress){var pattern=/^([a-z\d!#$%&'*+\-\/=?^_`{|}~\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]+(\.[a-z\d!#$%&'*+\-\/=?^_`{|}~\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]+)*|"((([ \t]*\r\n)?[ \t]+)?([\x01-\x08\x0b\x0c\x0e-\x1f\x7f\x21\x23-\x5b\x5d-\x7e\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]|\\[\x01-\x09\x0b\x0c\x0d-\x7f\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]))*(([ \t]*\r\n)?[ \t]+)?")@(([a-z\d\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]|[a-z\d\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF][a-z\d\-._~\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]*[a-z\d\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])\.)+([a-z\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]|[a-z\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF][a-z\d\-._~\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]*[a-z\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])\.?$/i;return pattern.test(emailAddress);};function email_newsletter_submit(email,$this){$this.find('.loadGif_news').show();$this.find('.success').hide();$this.find('.failure').hide();$this.find('.already').hide();$this.find('.formSubmit').fadeOut();var n_category=$this.find('#n_category').val();var n_type=$this.find('#n_type').val();var n_keyword=$this.find('#n_keyword').val();var n_location=$this.find('#n_location').val();var n_company=$this.find('#n_company').val();var post_id=$this.find('#post_id').val();jQuery.ajax({type:"POST",url:siteVars.ajaxURL,success:function(resultProp){resultProp=JSON.parse(resultProp);if(resultProp.result=='0'){$this.find('.success').hide();$this.find('.failure').show();$this.find('.already').hide();$this.find('.formSubmit').fadeIn();}
else if(resultProp.result=='1'){$this.find('.success').show();$this.find('.failure').hide();$this.find('.already').hide();$this.find('.formField').fadeOut();}
else if(resultProp.result=='2'){$this.find('.success').hide();$this.find('.failure').hide();$this.find('.already').show();$this.find('.formSubmit').fadeIn();}
$this.find('.loadGif_news').hide();console.log(resultProp);},data:{'action':'email_newsletter','userEmail':email,'n_category':n_category,'n_type':n_type,'n_keyword':n_keyword,'n_location':n_location,'n_company':n_company,'post_id':post_id}});}
if(jQuery('.jcf_display').length>0){jQuery('.jcf_display select').each(function(){var selectID=jQuery(this).attr('id');jcf.destroy(jQuery(this));jQuery(this).attr('data-jcf','{"wrapNative": false, "wrapNativeOnMobile": false, "fakeDropInBody": false, "useCustomScroll": false}');jcf.replace(jQuery(this));});}